# Site settings
title: SE @ MUICT
affiliation: Mahidol University, Thailand
email: chaiyong.rag@mahidol.ac.th, morakot.cho@mahidol.ac.th
description: >
  The website of the Software Engineering Research Unit (SERU) at the Faculty of ICT, Mahidol University.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://muict-seru.github.io # the base hostname & protocol for your site
git_address: https://github.com/MUICT-SERU

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: journal

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/London
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
